- source/howtos/upgrade/upgrade-61-to-62.rst
Hinweis auf Downloadmöglichkeit der linbo.iso
> Hinweis auf Downloadmöglichkeit der linbo.iso

- source/systemadministration/install-on-kvm/advanced.rst
- source/systemadministration/install-on-kvm/install.rst
- source/systemadministration/troubleshooting/softwarebugs.rst
Hallo Zuammen,
Ergänzung der KVM Installation des "servers":
* Linbo: Start Bittorrent Dienst
* Linbo: Anpassen der Startparameter des TFTPD Dienstes
und
* Anpassen des Verknüpfung zu den Softwarebugs, da die Navigation nicht i.O. war.
Grüße
> KVM Ergaenzung Installation

- source/about/about.rst
- source/about/release-information/index.rst
- source/getting-started/prerequisites/index.rst
- source/getting-started/serverinstallation/index.rst
Added sectionauthors with ask.linuxmuster.net handle and link
> add sectionauthors with ask.linuxmsuter.net handle and link

- source/appendix/install-on-xcp-ng/index.rst
Updated the Link for the new XCP-ng Center Management Software.
> Link for XCP-ng Center changed

- source/getting-started/install-on-xen/outlook.rst
further documentation for xenserver
> #109 - fix

- source/systemadministration/maintenance/migration.rst
> translate up to step 12

- source/appendix/install-on-kvm/index.rst
> fix broken compilation, change from md5 to sha-hashes

- source/index.rst
- source/systemadministration/maintenance/keep-lmn-uptodate.rst
Hallo Tobi,
hier mein Pull-Request!
Greetings
Tobi
> Mein erstes Hello World

- source/appendix/install-on-kvm/index.rst
- source/systemadministration/maintenance/migration.rst
make it clear that the folder structure needs to be /var/linbo
> migration tips

- source/getting-started/add-user-accounts/index.rst
- source/getting-started/prerequisites/index.rst
- source/getting-started/serverinstallation/index.rst
- besser für Neueinsteiger: keine Vorkenntnisse zu internas wie LINBO nötig.
- bessere Übersicht und Sortierung für die strukturellen Voraussetzungen/Vorbereitungen wie Festplattenplatz, Netzstruktur und  Virtualisierung.
> V7: Reorganisation Voraussetzungen

- source/systemadministration/network/networksegmentation/index.rst
> Some fixes regarding IPs in subnets.csv

- source/getting-started/installoptions/install-on-proxmox/index.rst
Change of the personal salutation and restructuring to the installation procedure
> Change of the personal salutation and restructuring

- source/getting-started/prerequisites.rst
Removal of the checksum description since moved to the Proxmox description. Was hidden in this file here anyway.
> Removal of the checksum description

- source/getting-started/installoptions/install-on-proxmox/index.rst
This fact is indicated on the relevant page.
> Proxmox instruction OVA does not work

- source/systemadministration/network/radius/index.rst
discussed here: https://ask.linuxmuster.net/t/neue-doku-kapitel-v7-online-radius-auf-dem-internen-server-externe-moodle-authentifizierung/5077/3
> security enhancements, typos, smaller rearrangements

- source/systemadministration/network/radius/index.rst
, die Firewall-Regel sollte zu den LAN-Regeln
> firewall auf dem lmn-server gibt es nicht mehr

- source/systemadministration/network/radius/index.rst
I reordered the chapter for implementing freeradius and implemented the adaption of the filter configuration as suggested by @garblixa and of the freeradius configuration authentification option as suggested by @zefanja.
> Fixed: #349 #106

- source/appendix/contribute/docs/guidelines.rst
- source/getting-started/installoptions/install-from-scratch/buildserver.rst
- source/getting-started/installoptions/install-from-scratch/media/link_arrow.svg
- source/getting-started/installoptions/install-on-kvm/index.rst
- source/getting-started/installoptions/install-on-kvm/media/link_arrow.svg
- source/getting-started/installoptions/install-on-proxmox/index.rst
- source/getting-started/installoptions/install-on-proxmox/media/link_arrow.svg
- source/getting-started/installoptions/install-on-xcp-ng/index.rst
- source/getting-started/installoptions/install-on-xcp-ng/media/link_arrow.svg
- source/getting-started/media/link_arrow.svg
- source/getting-started/prerequisites.rst
- source/getting-started/setup.rst
- source/guided_inst.subst
- source/index.rst
- source/media/link_arrow.svg
- source/systemadministration/network/preliminarysettings/index.rst
I have implemented this for the first branch and the merge regarding the selection of the installation type. Use the substitution of sqhinx to implement changes to the appearance by simply editing the file guided_inst.subst in the root directory. Explanation of all this is included in this file.  
Habe das erst einmal umgesetzt für die erste Verzweigung und die Zusammenführung bezüglich der Auswahl der Installationsart. Nutze dafür die substitution von sqhinx um Änderungen am Erscheinungsbild einfach mittels Eingriff in die Datei guided_inst.subst  im root-Verzeichnis umzusetzen. Erklärung des ganzen ist in dieser Datei eingearbeitet.
> Guided Installation by link_arrows #391

- source/getting-started/setup.rst
- source/guided_inst.subst
, so dass Erstkonfiguration alleinig links auftaucht……,
> fix überschriften, fix #405 dazu

- source/clients/linbo/linbo-mainscreen.rst
I searched some time ago for a clear info how to update the default linbo password.
I found some old wiki entries for e.g. here https://wiki.linuxmuster.net/archiv/dokumentation:handbuch60:linbo:configuration.linbopassword and thought it should be mentioned in the current documentation...
> Add info how to change linbo password

- README.rst
- source/systemadministration/network/radius/index.rst
Missing reference to the guidelines in the README.rst added. Preparations for #433
> Missing guidelines in README an Preparations for #433 

- source/getting-started/installoptions/install-on-proxmox/index.rst
As agreed: changed-Command-Style and small error corrections
> changed format of commands in code-style

- source/getting-started/installoptions/install-on-proxmox/index.rst
Thanks for the new virtual images to Chris
> Adaptation to the update of VM images from 19 of December

- source/about/what-is-new-in-7-0.rst
- source/classroom/exam-and-transfer.rst
- source/external-services/moodle/index.rst
- source/external-services/nextcloud/index.rst
- source/external-services/unifiwlan/unifischuelernetz.rst
- source/external-services/unifiwlan/unifivoucher.rst
- source/getting-started/harddisk/hard-drive-size-opnsense-vm.rst
- source/getting-started/harddisk/hard-drive-size-proxmox.rst
- source/getting-started/harddisk/index.rst
- source/getting-started/installoptions/index.rst
- source/getting-started/installoptions/install-from-scratch/buildopnsense.rst
- source/getting-started/installoptions/install-from-scratch/index.rst
- source/getting-started/installoptions/install-on-proxmox/index.rst
- source/getting-started/installoptions/install-on-xcp-ng/index.rst
- source/getting-started/migration/index.rst
- source/getting-started/network/networksegmentation/index.rst
- source/getting-started/network/preliminarysettings/index.rst
- source/getting-started/prerequisites.rst
- source/systemadministration/maintenance/keep-lmn-uptodate.rst
- source/systemadministration/network/default-access-rules.rst
- source/systemadministration/network/radius/index.rst
> Trademark OPNsense® checked

- source/classroom/exam-and-transfer.rst
> Update „Austeilen und Einsammeln“

- source/getting-started/installoptions/install-on-kvm/index.rst
Korrektur falsche Net-ID, bei do-it-like-babo
Schließt #516
> #516 fixed

- source/getting-started/network/segmentation/kvm_and_xcp-ng.rst
> Edit todo to test new branch as discussed with cweikl

- source/getting-started/linuxclient.rst
Result from a support request.
> Note box added to highlight the necessary procedure.

- source/getting-started/installoptions/install-on-kvm/import-kvm-vms.rst
- source/getting-started/installoptions/install-on-kvm/import-kvm-vms.rst_origirnal
- source/getting-started/installoptions/install-on-kvm/index.rst
- source/getting-started/installoptions/install-on-proxmox/import-proxmox-vms.rst
> Preparation of the KVM description for adoption according to the schedule.

- source/external-services/rocketchat/index.rst
> #551: first version of rocket.chat documentation - changed links

- source/systemadministration/printer/printer/1-infos.rst
Whoever finds it, prints it out with the date and time and gives it to me personally, I'll buy him or her a beer. But only to the one with the oldest printout.
This is a test of the "Edit on Github" function, as not write authorized new user.
Kind regards MachtDochNix
> one word added

- source/clients/add-computer.rst
- source/clients/linux-clients/linux-client-current-method.rst
Some additions, improvements and corrections.
> Some additions, improvements and corrections

- source/external-services/nextcloud/collabora.rst
Since a lot has changed in Collabora, I adapted the nginx.conf.
> Changes to Collabora

- source/external-services/nextcloud/collabora.rst
I added a brief description of how to update a Docker image.
> Further improvement

- source/installation/network/preliminarysettings/index.rst
Chapter Installation -> Network Preparation:
- according to new lmn71-prepare script the description how to prepare VMs with different network settings have been changed.
> v71: chapter installation - network peparation rewritten

- source/about/about.rst
@cweikl: I have reactivated the sections Alternative, Optional and Extra, because I think it is an important part of linuxmuster.net. For me it is even a unique selling point.
However, I think the formatting and the explanatory text make it more than obvious that they are not part of the present official documentation.
> Text and images revised

- source/about/about.rst
> V7.1 Placement of a graph Firewall adjusted

- source/installation/install-from-scratch/index.rst
Shortcut through the installation instructions for PROXMOX users.
> Guiding the installer through the instructions

- source/installation/install-from-scratch/basis_server.rst
- source/installation/install-from-scratch/lmn_pre_install.rst
Documentation improved, tested for lmn71-prepare (default configuration) and found to be better.
> V7.1 - Documentation tested until lmn71-prepare successfully switched off

- source/migration/linbo-migration-to-4.rst
richtigstellung bei den Paketnamen, das war verwirrend.
ich erstelle einen PR. Gleich committen mag ich nicht mehr machen, dafür ist zuviel passiert, von dem ich keine Ahnung habe.
> vorschlag linbo4 -> LINBO 4, Korrektur

- source/appendix/contribute/new.rst
- source/clients/client_templates/hardware_category/index.rst
- source/clients/client_templates/os_installation/linux-clients/index.rst
- source/empty-site-template_rename2rst
- source/external-services/dockerhost/index.rst
- source/installation/install-from-scratch/basis_server.rst
- source/installation/install-from-scratch/lmn_pre_install.rst
- source/migration/linux-client-migration.rst
- source/migration/migrate-from-6-2-to-7-1.rst
- source/migration/upgrade.rst
- source/setup/setup-console.rst
- source/systemadministration/harddisk/hard-drive-size-vm.rst
- source/systemadministration/printer/add-printers-with-cups.rst
- source/systemadministration/printer/configure-ad-group.rst
And another personal word replaced.
> Personal address corrected

- source/clients/client_templates/hardware_category/index.rst
- source/clients/client_templates/hardware_registration/index.rst
- source/clients/client_templates/index.rst
- source/clients/client_templates/os_installation/format_hdd_with_linbo.rst
- source/clients/client_templates/os_installation/index.rst
- source/clients/index.rst
- source/clients/linbo/index.rst2delete
- source/empty-site-template_rename2rst
- source/guided-inst.subst
- source/installation/install-from-scratch/basis_opnsense.rst
- source/installation/install-from-scratch/basis_server.rst
- source/installation/install-from-scratch/index.rst
- source/installation/install-from-scratch/lmn_pre_install.rst
- source/installation/proxmox/index.rst
- source/migration/migrate-from-6-2-to-7-1.rst
- source/setup/setup-console.rst
- source/systemadministration/harddisk/hard-drive-size-proxmox.rst
- source/systemadministration/harddisk/index.rst
Substitutions definition collected in one file
> Substitutions added

- source/installation/install-from-scratch/basis_server.rst
- source/installation/install-from-scratch/lmn_pre_install.rst
- source/setup/setup-console.rst
- source/setup/setup.rst
Better presentation and instructions for use.
> Update xterm.js for use

- source/external-services/aleksis/index.rst
- source/index.rst
@Supergamerx3000 wants to finalise this subchapter
> added new subchapter for external service aleksis

- source/external-services/aleksis/index.rst
Erste Version ich füge noch die LDAP Anbidung für Docker hinzu und die Filterung für Lehrer uns Schüler muss noch ergänzt werden. Da ist Aleksis aber gerade dabei die nochmal umzustellen deswegen warte ich dort noch auf die finale Aleksis Version.
> Update Aleksis LDAP Anbindung index.rst

- source/setup/setup-console.rst
Try to avoid any confusion about the address range for the first connection to the WebUI.
> First connection to the WebUI

- source/clients/client_templates/hardware_registration/index.rst
inserted general hint for device names
> fixed #785

- source/installation/install-from-scratch/lmn_pre_install.rst
see [github linuxmuster-prepare](https://github.com/linuxmuster/linuxmuster-prepare#readme)
> renaming lmn71-prepare to lmn-prepare

- source/clients/client_templates/hardware_category/index.rst
hint for kernel options to be used with linbo
> fixed #782

- source/setup/add-user-accounts.rst
Hints using a correct user name are given in a more prominent way.
> hints for addding teachers via management lists

- source/installation/install-from-scratch/lmn_pre_install.rst
fixed https://ask.linuxmuster.net/t/lmn-7-1-linuxmuster-prepare-webui-laeuft-nicht/8655/21
> fixed misunderstanduings in using lmn-prepare

- source/clients/use_linbo4/index.rst
see https://ask.linuxmuster.net/t/lmn-7-2-testing/9732/282
> added linbo hook-scripts

- source/migration/upgrade.rst
Hi Ihr,
schaut mal, ob ihr das mergen wollt.
Ich hab das RST nicht getestet :)
Vg, T.
> Jolly jump patch 1

- source/clients/use_linbo4/index.rst
- source/migration/linbo-migration-to-4.rst
- added Kernel-Options for LINBO v4.2
- added steps for changing Linux-Kernel for LINBO v4.2 on difficult hardware (thanks to Michael for your input
- still to be tested and revised
> added feature list vor linbo 4.2, added steps for testing spoky hardware

- source/clients/client_templates/os_installation/windows11clients/index.rst
- description of defprof
- description of reg patches
> Win11: fixes

- source/conf.py
- source/systemadministration/printer/add-printers-with-cups.rst
- source/systemadministration/printer/printers-windows-clients.rst
- jinja2 template not used by linuxmuster - fixed
> fixed conf.py

- source/classroom/exam-and-transfer.rst
- fixed description of exam mode according to hints given in https://ask.linuxmuster.net/t/problem-exam-modus-rechner-am-naechsten-tag-nicht-mehr-fuer-den-schueler-nutzbar/11605/30
> fixed description for exam mode

- source/about/what-is-new.rst
- source/index.rst
- source/migration/index.rst
- source/migration/upgrade.rst
- source/setup/setup.rst
- changes for Chapter What's new
> initial what's new infos for new v7.3 branch

- source/installation/install-from-scratch/basis_file_server.rst
- source/installation/install-from-scratch/index.rst
- source/installation/install-from-scratch/lmn_pre_install.rst
Revised complete chapter installation from scratch
- opnsense (optional)
- ad/dc server
- preparation of ad/dc server for lmn73 setup
- installation and preparation of lmn file-server
> revised installation-from-scratch - all parts - added file-server

- source/installation/install-from-scratch/basis_file_server.rst
- source/installation/install-from-scratch/proxmox_internes_netz.rst
- added new documentation for preparing a ubuntu 24.04 lts fileserver for lmn73
- revised description of  changing proxmox config for being part of lan
> inserted preparation of lmn73 fileserver

- source/migration/linbo-migration-to-4.rst
- source/migration/upgrade.rst
- added necessary stepf for upgrading an existing lmn v7.2 installation to v7.3
> fixed docu for upgrading to v7.3
